// src/database/models/Account.model.ts
import mongoose, { Schema, type Document, models, type Model } from "mongoose";

// Note: _id is automatically generated by MongoDB unless disabled.
// NextAuth adapter relies on the compound key { provider, providerAccountId }

export interface IAccount extends Document {
  userId: mongoose.Types.ObjectId;
  type: string;
  provider: string;
  providerAccountId: string;
  refresh_token?: string;
  access_token?: string;
  expires_at?: number;
  token_type?: string;
  scope?: string;
  id_token?: string;
  session_state?: string;
  // user: mongoose.Types.ObjectId; // Ref back to User - handled by userId
}

export const AccountSchema: Schema<IAccount> = new Schema(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true },
    type: { type: String, required: true },
    provider: { type: String, required: true },
    providerAccountId: { type: String, required: true },
    refresh_token: { type: String },
    access_token: { type: String },
    expires_at: { type: Number },
    token_type: { type: String },
    scope: { type: String },
    id_token: { type: String },
    session_state: { type: String },
  },
  {
    timestamps: true,
    // _id: false, // Generally keep _id unless you have a strong reason not to
  }
);

// Compound index required by NextAuth adapter for provider uniqueness
AccountSchema.index({ provider: 1, providerAccountId: 1 }, { unique: true });
// Index userId for efficient lookups relating accounts to users
AccountSchema.index({ userId: 1 });

const AccountModel: Model<IAccount> =
  models.Account || mongoose.model<IAccount>("Account", AccountSchema);
export default AccountModel;
